# Generated by Django 2.2.9 on 2020-02-12 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Назва пакета")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Скільки днів діє пакет",
                        null=True,
                        verbose_name="Строк дії",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Скільки дзвінків містить пакет",
                        null=True,
                        verbose_name="Кількість дзвінків",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Чи доступний пакет для замовлення"
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Скільки коштує пакет (тільки цифра)",
                        null=True,
                        verbose_name="Вартість",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Опис пакета", null=True),
                ),
                (
                    "order",
                    models.IntegerField(
                        blank=True,
                        help_text="Порядок сортування",
                        null=True,
                        verbose_name="Порядок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пакет",
                "verbose_name_plural": "Пакети",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserCall",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Дзвінок зараховано",
                        verbose_name="Підтверджено",
                    ),
                ),
                (
                    "answered_by",
                    models.ForeignKey(
                        help_text="Фахівець",
                        limit_choices_to=models.Q(groups__name="Фахівці"),
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answered_calls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Фахівець",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Менеджер",
                        limit_choices_to=models.Q(groups__name="Менеджери"),
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Менеджер",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        help_text="Тема",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="home.Theme",
                        verbose_name="Тема",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Замовник",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клієнт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дзвінок",
                "verbose_name_plural": "Дзвінки",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="PackageOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "date_start",
                    models.DateField(
                        help_text="З якої дати активовано пакет",
                        verbose_name="дата початку",
                    ),
                ),
                (
                    "date_end",
                    models.DateField(
                        help_text="До якої дати активовано пакет",
                        verbose_name="дата завершення",
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Оплату підтверджено",
                        verbose_name="Підтверджено",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        help_text="Пакет",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orders.Package",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Замовник",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Замовлення",
                "verbose_name_plural": "Замовлення",
                "ordering": ["-created"],
            },
        ),
    ]
