# Generated by Django 2.2.9 on 2020-01-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Назва")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Чи активна тема"),
                ),
                (
                    "order",
                    models.IntegerField(
                        blank=True,
                        help_text="Порядок сортування",
                        null=True,
                        verbose_name="Порядок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тема",
                "verbose_name_plural": "Теми",
                "ordering": ["name"],
            },
        ),
    ]
